import  math
print ( math.sqrt(1))
print ( math.sqrt(4))
print ( math.sqrt(9))
print ( math.sqrt(16))
print ( math.sqrt(25))
print ( math.sqrt(36))
print ( math.sqrt(49))
print ( math.sqrt(64))
print ( math.sqrt(81))
print ( math.sqrt(100))